-- MySQL Script generated by MySQL Workbench
-- dom 16 sep 2018 01:11:35 EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `age` INT(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` LONGTEXT NOT NULL,
  `latitude` FLOAT NOT NULL,
  `longitude` FLOAT NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BBQ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BBQ` (
  `idBBQ` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) NOT NULL,
  `photo` VARCHAR(45) NULL,
  `latitude` FLOAT NOT NULL,
  `BBQcol` FLOAT NOT NULL,
  PRIMARY KEY (`idBBQ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rent` (
  `User_idUser` INT NOT NULL,
  `BBQ_idBBQ` INT NOT NULL,
  PRIMARY KEY (`User_idUser`, `BBQ_idBBQ`),
  INDEX `fk_User_has_BBQ_BBQ1_idx` (`BBQ_idBBQ` ASC),
  INDEX `fk_User_has_BBQ_User_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_User_has_BBQ_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_BBQ_BBQ1`
    FOREIGN KEY (`BBQ_idBBQ`)
    REFERENCES `mydb`.`BBQ` (`idBBQ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LikeBBQ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LikeBBQ` (
  `User_idUser` INT NOT NULL,
  `BBQ_idBBQ` INT NOT NULL,
  PRIMARY KEY (`User_idUser`, `BBQ_idBBQ`),
  INDEX `fk_User_has_BBQ_BBQ2_idx` (`BBQ_idBBQ` ASC),
  INDEX `fk_User_has_BBQ_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_User_has_BBQ_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_BBQ_BBQ2`
    FOREIGN KEY (`BBQ_idBBQ`)
    REFERENCES `mydb`.`BBQ` (`idBBQ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
